	<div class="container-fluid">
		<div class="row" style="height: 300px;">
		</div>
		<div class="row alert alert-danger align-items-center" style="height: 300px;">
			<div class="col-sm">
			</div>
			<div class="col-sm">
				<h1 class="display-4">Algo Deu Errado!</h1>
				<hr>
				<p class="lead"><?php echo $this->message; ?></p>
				<a href="/"><button class="btn btn-danger">Voltar</button></a>
			</div>
			<div class="col-sm">
			</div>
		</div>
	</div>
</body>
</html>